old_emails = """souzaalex0248@gmail.com
alexpagniez@gmail.com
alexandrebarbosa042@gmail.com
alexandre.barbosa.nascimento@gmail.com
alicebianchiinimrs@gmail.com
alineduncan@gmail.com
amarildo.pereira@gmail.com
amarojaperi331@gmail.com
amelia.santos@gmail.com
anacarlarj@hotmail.com
anapaulabercotsilva@gmail.com
andrelohan777@icloud.com
andreiadesouza2376@gmail.com
andrecarioca800@gmail.com
andreluizlaureano1976@gmail.com
andrewasley@gmail.com
angmaria1988@gmail.com
nemitzangela22@gmail.com
angelica.dias.oliveira@gmail.com
anilza.araujo002@gmail.com
lucileneantonia@gmail.com
toninho_ns@hotmail.com
biaribeiro@gmail.com
brendhaquintadilha123@gmail.com
bruno.brito.silva@gmail.com
bgonçalvesolkveira@gmail.com
cailan.cardoso@gmail.com
camilaabreudeoliveiraesteves@gmail.com
carlos.moraes@gmail.com
carlosestofadosni@gmail.com
alexandrecarlos@gmail.com
barretolou@hotmail.com
carlinhos333@gmail.com
carlos.correa.firmo@gmail.com
rodriguescauelucas3103@gmail.com
caduneves1@gmail.com
calosjose@gmail.com
carlos.menin@gmail.com
carlos.ricardo.mendonca@gmail.com
netvinyeugenio@hotmail.com
clarissaadv83@gmail.com
cristian.souza.mello@gmail.com
cristianjardim18@gmai.com
cris.kadupeixoto@gmail.com
cristianesampaio2409@gmail.com
cezar.sacramento.alves@gmail.com
daiannacristinna@icloud.com
darr89.da@gmail.com
diclima42@gmail.com
daniramos22@gmail.com
dani.dasilvarangel@gmail.com
danisouza194@hotmail.com
danielleramosdp@gmail.com
daniellevcosta187@gmail.com
danielson.borges@gmail.com
santosdeborah58@gmail.com
nocogomesdapenha@gmail.com
denilsanton@gmail.com
denioaferreira@gmail.com
garcezdenis46@gmail.com
diana.silva@gmail.com
diego.campos.gomes@gmail.com
diogomartinsrj4@gmail.com
dilceia.vieira@gmail.com
ederson.souza@gmail.com
edsandro624@gmail.com
edsoncabral8239@gmail.com
eduardojunqueira37@gmail.com
elexandra lisboa@gmail.com
lianelealribeiro@gmail.com
elisangela.mota@gmail.com
elizabethcostahjh@gmail.com
emersonramos1502@gmail.com
ds1119629@gmail.com
cenzo15@yahoo.com
erick.bloise.lima@gmail.com
erikamaedakika2@gmail.com
esteiroribeiro@hotmail.com
eversonribeiro2025@gmail.com
everton.silva@portosrio.temp.br
expeditoguimaraes247@gmail.com
fabiano.pereira.rocha@gmail.com
fabiosants555@gmail.com
fatima.azevedo@portosrio.temp.br
fenelassed@hotmail.com
feeprince19@gmail.com
fernanda.fernandes@gmail.com
fernandoboechatjr@hotmail.com
flavioconceicao15@gmail.com
fcchlcomento1954@hotmail.com
francisconatao000@gmail.com
gcg.0014@gmail.com
gabrielcsantos234@gmail.com
gabrielgoulartdearaujo@gmail.com
gabpereira@gmail.com
gabrielsymeonegerl@gmail.com
gabivirgo128@gmail.com
gabizzinhahenriques@gmail.com
gabiolinda@gmail.com
gabriella.dg2018@hotmail.com
genilson.santos.silva@gmail.com
georgecosmenascimento@gmail.com
geeh.gravessem@gmail.com
geysongramos@gmail.com
gilgomesrj@gmail.com
pedrogilson2019@agmail.com
gizele.conceicao.santos@gmail.com
greicegov@gmail.com
gressyrenner23@gmail.com
guigas.campos@gmail.com
hanna0033@gmail.com
heitor.assis@gmail.com
helena.ribeiro.nunes@gmail.com
henrique.soares.silva@gmail.com
hewfer@gmail.com
heynegm21@gmail.com
hugo.zevedo@gmail.com
igorbeneditoprimeiro@gmail.com
inara.goncalves@gmail.com
isabellabarbosa034@gmail.com
itamar.teixeira@gmail.com
jaderjuniorcordeiro@gmail.com
lenomorais23@gmail.com
jair.cunha@gmail.com
jane.souza@portosrio.temp.br
jane.gomes@gmail.com
jaquemerçam@gmail.com
jefferson.alerj@gmail.com
jeferson_andre10@gmail.com
jeniffer.silvans@gmail.com
jessepires12@gmail.com
jb3772083@gmail.com
xavierjosecarlosx@gmail.com
zegalo000@gmail.com
jgsobrinho12@gmail.com
joseraimujndo423@gmail.com
joselia.emilia.silva@gmail.com
jojopelle@gmail.com
jose.lisboa.pereira@gmail.com
josefaria332@gmail.com
grasiflordepaulo@gmail.com
joyce.ramosclei@gmail.com
joaogomesportorea@gmail.com
eliasbrito 123@gmail.com
joaolucas.vilela@gmail.com
dossantosjoaovitorleandro@gmail.com
aparecidajulia3002@gmail.com
jucortespon@gmail.com
juhbarrinha@gmail.com
falarcomjuliogomes@gmail.com
jurandimatos000@gmail.com
katiapinheiro1986@gmail.com
kaupinheiro@gmail.com
kellygomesmonteiro3@gmail.com
kelly.lucia.benvindo.batista.canust@gmail.com
lairacristina915@gmail.com
laiza.vellozo@icloud.com
laripessanha@gmail.com
leandro.goncalves.tiago@gmail.com
pr.sperendio@gnail.com
leonardobmoreira@live.com
leonardo06barbosa@gmail.com
leticiia.silva2505@gmail.com
lidiane.alencar.ponce.gomes@gmail.com
lidiane.santos.moreira@gmail.com
liviasouza2110@gmail.com
livyadiniz8@gmail.com
lorranrodrigues4@gmail.com
lorranagomes.adv@amail.com
luana.prazeres@portosrio.temp.br
lucasolisouzapj@gmail.com
lucas.ferreira.silva@gmail.com
lucassantos@gmail.com
lucasrangelgomesperes@gmail.com
lucilene.barbosa@portosrio.temp.br
luisnovellinomarques@gmail.com
luisotaviogomespereira1234@hotmail.com
luiztimbauba82@gmail.com
maicon.soares91@gmail.com
maracriatinalaura@gmail.com
marcel.correa@hotmail.com
marcelapacienciapereira@gmail.com
marcelocamposdas@gmail.com
marceeva643@gmail.com
diretormegamix@gmail.co
marciaferreira.1805@gmail.com
marciavictorfrazao@gmail.com
marcio.muniz@portosrio.temp.br
marcoantonio.paes@gmail.com
mabbarros@yahoo.com.br
marcosfelix452023@gmail.com
marcospeixotosoaresp@gmail.com
mvsouzapinturas3@gmail.com
lizacamylle@hotmail.com
mariaalmeida 123@gmail.com
mariaaahcalvacanti234@gmail.com
mariacleiderj@gmail.com
msoarespereira19@gmail.com
pablocontagp@gmail.com
mariasilvavalentim19@gmail.com
marianaveira000@gmail.com
marianafarias3110@gmail.com
marlon1coelho1234@gmail.com
mateus.vieira.teixeira@gmail.com
matheus.quintal@portosrio.temp.br
matheusstellet922@gmail.com
mausouza@gmail.com
omaxslei@gmail.com
maxwellmariadasilva@gmail.com
maycon.senra@hotmail.com
millenariopsi@gmail.com
moacirfilho10@gmail.com
murilovieira10@hotmail.com
nathalicsbarros@gmail.com
nathaliadasilvavalente2020@gmail.com
nathaliafrancelino1@gmail.com
nathalia.sperendio.oliveira@gmail.com
nathielly.sophi/2gmail.com
nubia.estevao@gmail.com
osirisamaral7@gmail.com
osfer@gmail.com
ostairferreira@gmail.com
pablorhuanbuffa@gmail.com
castilhopaola373@gmail.com
paulo.carvalho.silva@gmail.com
peterson212709@gmail.com
22997958734pae@gmail.com
priscilla.gama@portosrio.temp.br
rafael.dias.ribeiro@gmail.com
rafaoliveiralima07@gmail.com
pedroregisgato0508@gmail.com
raimundononatodesouza199@gmail.com
raissabrito680@gmail.com
raquelcorrea55@gmail.com
raul.nascimento@gmail.com
reginaldovalentim050@gmail.com
souzarenata321@gmail.com
richardison.ri@hotmail.com
rn06456@gmail.com
rogerio.jose.silva@gmail.com
rogerioeletrica@gmail.com
rogerodrigues199@gmail.com
roldiney.terrason@gmail.com
rosanaamaral184@gmail.com
sanfreitas@gmail.com
sandra.rosa.santana.jesus@gmail.com
sergio.alves.ceda@gmail.com
sfseveriano@hotmail.com
nerysergioso@hotmail.com
silvani.maria25@gmail.com
smatrb.maciel@gmail.com
silvio.santos.souza@gmail.com
simone.aparecida.menezes.abreu@gmail.com
simone.regina.teixeira@gmail.com
sornandes@gmail.com
suelen.maisa.lipe@gmail.com
smirandadama@gmail.com
suzelane.macario.barros.paula@gmail.com
soaniawerneck05@gmail.com
taise.cavallieri@gmail.com
tsreserva.1@gmail.com
lindinhatatiana06@gmail.com
tatiane.nunes.mota@gmail.com
thdomingoss022@gmail.com
titimacuco@gmail.com
valdecir.madeira@portosrio.temp.br
valeria.machado.silva@gmail.com
floridovaleria66@gmail.com
vanderlei.correa789@gmail.com
vanderleyronan@gmail.com
victor.moraes@portosrio.temp.br
victorocs@gmail.com
virgilio.panissolo.pereira@gmail.com
vvjales@gmail.com
vitorcorreafotografo@gmail.com
vhcruz2003@gmail.com
vitoriamontes58@gmail.com
ivianeangelidarodrigues@gmail.com
sodanii@yahoo.com.br
vitrini123alves@hotmail.com
warlocarvalhosumi@gmail.com
webson.silva.santos1@gmail.com
wellingtonwado160@gmail.com
w.lacerda2028@gmail.com
alencarsilva369@gmail.com
wilsonfranca555@gmail.com
yuridesousatelleslopes@gmail.com
alvari@gmail.com
adriano.rodrigues.araujo@gmail.com
adriele.melo@live.com
ailtonmendonça333@gmail.com
ASSISGRADES@GMAIL.COM
alessandro.rocha.paura@gmail.com
aj4605480@gmail.com
alexandre.januario@gmail.com
ana.carla.lima.pereira@gmail.com
aanalaura880@gmail.com
analuizapessanha414@gmail.com
floranasouza1@gmail.com
anderson.rodrigues.oliveira@gmail.com
rodrigues.dessa.1989@gmail.com
andrynedepaulal6@gmall.com
ANGELINAANINHA02@GMAIL.COM
antonio.alison.costa.matias@gmail.com
bruno.accioli.costa@gmail.com
brunocarvalho.gestao@gmail.com
bruno.dorna.souza@gmail.com
Camila.alencar.cortes@gmail.com
camila.martins.leal.nascimento@gmail.com
carlos.alberto.souza@gmail.com
CARLOSESTOFADOSNI@GMAIL.COM
carlos.ribeiro.simoes@hotmail.com
carolinemayara800@gmail.com
clayton.santos.liberatori@gmail.com
cleber.siqueira.silva.pereira@gmail.com
daniel.teixeira.souza@gmail.com
dayanadiniz468@gmail.com
demetrius.figueiredo@gmail.com
elaine.moraes.sanches@gmail.com
ELISAARAUJO@GMAIL.COM
manuh_ivanovich@hotmail.com
emerson.leonardo.silva.gomes@gmail.com
FABIOSILVA@GMAIL.COM
fatimacarvalhoo804@gmail.com
fernando.cruz.silva@gmail.com
GABRIELGORGESWERNECK@GMAIL.COM
henrique.carvalho.pereira@gmail.com
henrique.jesus.silva.ferreira@gmail.com
isac.sales@gmail.com
israel.cesar.marques.junior@gmail.com
israel.valdevido.limeira@gmail.com
IZABELLAMRODRIGUES2001@GMAIL.COM
jaime.souza.sa@gmail.com
jefferson.matos.assis@gmail.com
jilvania.soares.mota.albino@gmail.com
lpnjhon@gmail.com
jordanna.lima24@gmail.com
JOSEERIVA@GMAIL.COM
joseleandrocampelocardoso@gmail.com
jose.garcia.castro@gmail.com
joyce.goncalves.souza@gmail.com
julio.cesar.lourenco.silva@gmail.com
julio.cesar.lourenco.silva.junior@gmail.com
julio.cezar.souza.silva@gmail.com
LEANDROPONTES323@GMAIL.COM
leonardo.junior.lima.sacramento@gmail.com
LETHICIASANTOSSS@GMAIL.COM
lucas.messias.moraes@gmail.com
LUCIENEROCHA@GMAIL.COM
FELIPE.021@HOTMAIL.COM
L.PHELIE@GMAIL.COM
LUIZACALAZANS11@ICLOUD.COM
magno.furtado.nobrega@gmail.com
marco.bastos@gmail.com
mariaangelbrandao25@gmail.com
MARIOPEREIRA19222@HOTMAIL.COM
marisa.farroco.tavares.azevedo@gmail.com
matheus.moura.costa@gmail.com
JRDOPULAPULA2248@GMAIL.COM
MAXUEL.BATISTA1978@GMAIL.COM
michel.anderson.belmira.souza@gmail.com
eunataliamiranda@hotmail.com
AUGUSTOPABLO408@GMAIL.COM
3p.pablo@gmail.com
PATRICIA.CORTES@GMAIL.COM
POLIAMRAL@GMAIL.COM
priscila.menechini@gmail.com
rafael@Gmail.com
rafael.luciano.faustino.silveira@gmail.com
ralfe.assad.rodrigues@gmail.com
ramon.verissimo.santos@gmail.com
renan.teixeira.c@hotmail.com
sandrelilourenco22@gmail.com
silvana.teixeira.abreu@gmail.com
CARDOSOLOIRA50@GMAIL.COM
pontestatiana1984@gmail.com
THAICPENF@GMAIL.COM
To788484@gmail.com
contatotiagomedeiros@hotmail.com
uilian.cardoso.santos@gmail.com
vinicius.vmo@gmail.com
wanderson.paes.leme.silva@gmail.com
BORGESWILLIA852@GMAIL.COM
yagofidalgo@gmail.com""".split("\n")

new_emails = """souzaalex0248@gmail.com
alexandercamargoest@outlook.com
alexandrenascimentoest@outlook.com
alexandresantosest@outlook.com
alicestorkest@outlook.com
alinesoaresest@outlook.com
amarildopereiraest@outlook.com
amaronetoest@outlook.com
ameliasantosest@outlook.com
anacarlasantosest@outlook.com
anabercotest@outlook.com
andrevieiraest@outlook.com
andreiasouzaest@outlook.com
andreversongoncalvesest@outlook.com
andreloureanoest@outlook.com
andrefirmoest@outlook.com
angelasantosest@outlook.com
angelaoliveiraest@outlook.com
angelicaoliveiraest@outlook.com
anilzaaraujoest@outlook.com
antoniamendesest@outlook.com
carlos_souzaest@outlook.com
beatrizrochaest@outlook.com
brendhadiasest@outlook.com
brunosilvaest@outlook.com
brunooliveiraest@outlook.com
cailancardosoest@outlook.com
camilaoliveiraest@outlook.com
carlosmoraesest@outlook.com
carlosestofadosni@gmail.com
carlosgomesest@outlook.com
carlosloureiroest@outlook.com
carlosmedeirosest@outlook.com
carlosfirmoest@outlook.com
carloslimaest@outlook.com
carlosnevesest@outlook.com
carlossouzaest@outlook.com
carlosmeninest@outlook.com
carlosmendoncaest@outlook.com
celinaeugenioest@outlook.com
clarissaleopoldinoest@outlook.com
cristianmelloest@outlook.com
cristiannanascimentoest@outlook.com
cristianecarvalhoest@outlook.com
cristianesampaiorest@outlook.com
cezaralvesest@outlook.com
daianegouveaest@outlook.com
danielribeiroest@outlook.com
daniellimaest@outlook.com
danielamancoest@outlook.com
danielasilvaest@outlook.com
daniellelimaest@outlook.com
danielleramosest@outlook.com
daniellecostaest@outlook.com
danielsonborgesest@outlook.com
deborahbarreirosest@outlook.com
dejacirpenhaest@otulook.com
denilciasantoest@outlook.com
denioferreiraest@outlook.com
denisgarcez@outlook.com
dianasilvaest@outlook.com
diegogomesest@outlook.com
diegomartinsest@outlook.com
dilceiavieiraest@outlook.com
edersonsouzaest@outlook.com
edsandromerlinest@outlook.com
edsonjuniorest@outlook.com
eduardojunqueiraest@outlook.com
elexandraamaranteest@outlook.com
elianeribeiroest@outlook.com
elisangelamotaest@outlook.com
elizabethlimaest@outlook.com
emersonromoaldoest@outlook.com
enirsilvaest@outlook.com
enzopintorest@outlook.com
ericklimaest@outlook.com
erikasouzaest@outlook.com
estesiodantesest@outlook.com
eversonribeiroest@outlook.com
evertonsilvaest@outlook.com
expeditosilvaest@outlook.com
fabianorochaest@outlook.com
fabiomourasantosest@outlook.com
fatimaazevedoest@outlook.com
fenelaassedest@outlook.com
fernandapachecoest@outlook.com
fernandafernandesest@outlook.com
fernandojuniorest@outlook.com
flavioconceicaoest@outlook.com
franciscomendesest@outlook.com
franciscoferreiraest@outlook.com
gabrielalvesest@outlook.com
gabriel_santosest@outlook.com
gabrielmacedoest@outlook.com
gabrielsilvaest@outlook.com
gabrielsymeonegerl@gmail.com
gabrielsantosest@outlook.com
gabrielahenriquesest@outlook.com
gabriellacastroest@outlook.com
gabirellasilvaest@outlook.com
genilsonsilvaest@outlook.com
georgenascimentoest@outlook.com
geovanisantosest@outlook.com
geysonsilvaest@outlook.com
gilmargomesest@outlook.com
gilsonpedroest@outlook.com
gizelesantosest@outlook.com
greicesouzaest@outlook.com
gresyferreiraest@outlook.com
guidopessanhaest@outlook.com
hannapereiraest@outlook.com
heitorassisest@outlook.com
helenaribeiroest@outlook.com
henriquesilvaest@outlook.com
hewertonsouzaest@outlook.com
heynemartinsest@outlook.com
hugozevedoest@outlook.com
igorcamposest@outlook.com
inaragoncalvesest@outlook.com
isabelasantosest@outlook.com
itamarteixeiraest@outlook.com
jaderalmadaest@outlook.com
jailtonsouzaest@outlook.com
jaircunhaest@outlook.com
janesouzaest@outlook.com
janegomesest@outlook.com
jaquelinemercamest@outlook.com
jefersongomesest@outlook.com
jefersonvianaest@outlook.com
jeniffersilvaest@outlook.com
jesserochaest@outlook.com
jonatanfurrielest@outlook.com
josexavierest@outlook.com
josegalloest@outlook.com
josesobrinhoest@outlook.com
josedesouzaest@outlook.com
joseliasilvaest@outlook.com
josianepellegriniest@outlook.com
jose.lisboa.pereira@gmail.com
josefariaest@outlook.com
grasiflordepaulo@gmail.com
joycesilvaest@outlook.com
joagomesest@outlook.com
joaobritoest@outlook.com
joaovilelaest@outlook.com
joaosantosest@outlook.com
juliaaraujosest@outlook.com
juliapontesest@outlook.com
julianaoliveiraest@outlook.com
juliogomesest@outlook.com
jurandirbrandaoest@outlook.com
katiapinheiroest@outlook.com
kauansouzaest@outlook.com
kellysouzaest@outlook.com
kellycanustest@outlook.com
lairasoaresest@outlook.com
laizagilest@outlook.com
larissapessanhaest@outlook.com
leandrotiagoest@outlook.com
pr.sperendio@gmail.com
leonardomoreiraest@outlook.com
leonardobarbosaest@outlook.com
leticiaguilhermeest@outlook.com
lidianegomesest@outlook.com
lidianemoreireaest@outlook.com
liviasouzaest@outlook.com
livycostaest@outlook.com
lorranrodriguesest@outlook.com
lorransouzaest@outlook.com
luanaprazeresest@outlook.com
lucassouzaest@outlook.com
lucassilvaest@outlook.com
lucas_santosest@outlook.com
lucasperesest@outlook.com
lucilenebarbosaest@outlook.com
luismarquesest@outlook.com
luispereiraest@outlook.com
luizsantosest@outlook.com
maiconsoaresest@outlook.com
maracostaest@outlook.com
marceltavaresest@outlook.com
marcelapacienciapereira@gmail.com
marcelobaptistaest@outlook.com
marcelovieiraest@outlook.com
marcelolamenhaest@outlook.com
marciasouzaest@outlook.com
marciafrazaoest@outlook.com
marciomunizest@outlook.com
marcopaesest@outlook.com
marcossilvaest@outlook.com
marcosfelixest@outlook.com
marcossoaresest@outlook.com
marcussouzaest@outlook.com
mariaaparecidaest@outlook.com
marianaalmeidaest@outlook.com
mariadesouzaest@outlook.com
marialimaest@outlook.com
mariapereiraest@outlook.com
mariaeduardaliraest@outlook.com
mariavalentimest@outlook.com
marianavieiraest@outlook.com
marianafariaest@outlook.com
marloncoelhoest@outlook.com
mateusteixeiraest@outlook.com
matheusquintalest@outlook.com
matheusalmeidaest@outlook.com
mausouza@gmail.com
maxsleisilvaest@outlook.com
maxuelsilvaest@outlook.com
mayconsilvaest@outlook.com
milenapereiraest@outlook.com
moacirfilhoest@outlook.com
murilovieiraest@outlook.com
nathalibarrosest@outlook.com
nathaliavalenteest@outlook.com
nathaliafrancelinoest@outlook.com
nathaliaoliveiraest@outlook.com
nathiellyfreitasest@outlook.com
nubiaestevaoest@outlook.com
osirisjuniorest@outlook.com
osmarjuniorest@outlook.com
ostayrfilhoest@outlook.com
pablooliveiraest@outlook.com
paolasilvaest@otutlook.com
paulosilvaest@outlook.com
petersonrochaest@outlook.com
polyanarangelest@outlook.com
priscillagamaest@outlook.com
rafaelribeiroest@outlook.com
rafael_limaest@outlook.com
raianeoliveiraest@outlook.com
raimundosouzaest@outlook.com
raissabritoest@outlook.com
raquelsilvaest@outlook.com
raulnascimentoest@outlook.com
reginaldosilvaest@outlook.com
renatasouzaest@outlook.com
richardisonbragaest@outlook.com
rodrigonascimentoest@outlook.com
rogeriosilvaest@outlook.com
rogerioeletrica@gmail.com
rogerodrigues199@gmail.com
roldineyterrasonest@outlook.com
rosanachaimest@outlook.com
sandrasouzaest@outlook.com
sandradejesusest@outlook.com
sergioalencarest@outlook.com
sergioseverianoest@outlook.com
sergiooliveiraest@outlook.com
silvaniconceicaoest@outlook.com
silviamacielest@outlook.com
silviosouzaest@outlook.com
simoneabreuest@outlook.com
simoneteixeiraest@outlook.com
soratoandreest@outlook.com
suelenoliveiraest@outlook.com
suelidamaest@outlook.com
suzelanepaulaest@outlook.com
soniawerneckest@outlook.com
taisevieiraest@outlook.com
talitasantosest@outlook.com
tatianarodriguesest@outlook.com
tatianemotaest@outlook.com
thiagosouzaest@outlook.com
tiagosilvaest@outlook.com
valdecirmadeiraest@outlook.com
valeriasilvaest@outlook.com
valeriasouzaest@outlook.com
vanderleisouzaest@outlook.com
vanderleyalvesest@outlook.com
victormoraesest@outlook.com
victorsilvaest@outlook.com
virgiliopereiraest@outlook.com
virgmonteiroest@outlook.com
vitorsantosest@outlook.com
vitorsilvaest@outlook.com
vitoriasouzaest@outlook.com
vivianerodriguesest@outlook.com
wallacemoreiraest@outlook.com
walteralvesest@outlook.com
warloncarvalhoest@outlook.com
websonsantosest@outlook.com
wellingtonoliveiraest@outlook.com
wellingtonlimaest@outlook.com
willianalencarest@outlook.com
wilsonfrancaest@outlook.com
yurilopesest@outlook.com
alvaroleixasest@outlook.com
adriano.rodrigues.araujo@gmail.com
adriele.melo@live.com
ailtonmendonça333@gmail.com
ASSISGRADES@GMAIL.COM
alessandro.rocha.paura@gmail.com
aj4605480@gmail.com
alexandre.januario@gmail.com
ana.carla.lima.pereira@gmail.com
aanalaura880@gmail.com
analuizapessanha414@gmail.com
floranasouza1@gmail.com
anderson.rodrigues.oliveira@gmail.com
rodrigues.dessa.1989@gmail.com
andrynedepaulal6@gmall.com
ANGELINAANINHA02@GMAIL.COM
antonio.alison.costa.matias@gmail.com
bruno.accioli.costa@gmail.com
brunocarvalho.gestao@gmail.com
bruno.dorna.souza@gmail.com
Camila.alencar.cortes@gmail.com
camila.martins.leal.nascimento@gmail.com
carlos.alberto.souza@gmail.com
CARLOSESTOFADOSNI@GMAIL.COM
carlos.ribeiro.simoes@hotmail.com
carolinemayara800@gmail.com
clayton.santos.liberatori@gmail.com
cleber.siqueira.silva.pereira@gmail.com
daniel.teixeira.souza@gmail.com
dayanadiniz468@gmail.com
demetrius.figueiredo@gmail.com
elaine.moraes.sanches@gmail.com
ELISAARAUJO@GMAIL.COM
manuh_ivanovich@hotmail.com
emerson.leonardo.silva.gomes@gmail.com
FABIOSILVA@GMAIL.COM
fatimacarvalhoo804@gmail.com
fernando.cruz.silva@gmail.com
GABRIELGORGESWERNECK@GMAIL.COM
henrique.carvalho.pereira@gmail.com
henrique.jesus.silva.ferreira@gmail.com
isacsalesest@outlook.com
israel.cesar.marques.junior@gmail.com
israel.valdevido.limeira@gmail.com
IZABELLAMRODRIGUES2001@GMAIL.COM
jaime.souza.sa@gmail.com
jefferson.matos.assis@gmail.com
jilvania.soares.mota.albino@gmail.com
lpnjhon@gmail.com
jordanna.lima24@gmail.com
josesilvaest@outlook.com
joseleandrocampelocardoso@gmail.com
jose.garcia.castro@gmail.com
joyce.goncalves.souza@gmail.com
julio.cesar.lourenco.silva@gmail.com
julio.cesar.lourenco.silva.junior@gmail.com
julio.cezar.souza.silva@gmail.com
LEANDROPONTES323@GMAIL.COM
leonardo.junior.lima.sacramento@gmail.com
LETHICIASANTOSSS@GMAIL.COM
lucas.messias.moraes@gmail.com
LUCIENEROCHA@GMAIL.COM
FELIPE.021@HOTMAIL.COM
L.PHELIE@GMAIL.COM
LUIZACALAZANS11@ICLOUD.COM
magno.furtado.nobrega@gmail.com
marco.bastos@gmail.com
mariaangelbrandao25@gmail.com
MARIOPEREIRA19222@HOTMAIL.COM
marisa.farroco.tavares.azevedo@gmail.com
matheus.moura.costa@gmail.com
mauricioteixeiraest@outlook.com
MAXUEL.BATISTA1978@GMAIL.COM
michel.anderson.belmira.souza@gmail.com
eunataliamiranda@hotmail.com
AUGUSTOPABLO408@GMAIL.COM
3p.pablo@gmail.com
PATRICIA.CORTES@GMAIL.COM
POLIAMRAL@GMAIL.COM
priscila.menechini@gmail.com
rafael@Gmail.com
rafael.luciano.faustino.silveira@gmail.com
ralfe.assad.rodrigues@gmail.com
ramon.verissimo.santos@gmail.com
renan.teixeira.c@hotmail.com
sandrelilourenco22@gmail.com
silvana.teixeira.abreu@gmail.com
CARDOSOLOIRA50@GMAIL.COM
pontestatiana1984@gmail.com
THAICPENF@GMAIL.COM
To788484@gmail.com
contatotiagomedeiros@hotmail.com
uilian.cardoso.santos@gmail.com
vinicius.vmo@gmail.com
wanderson.paes.leme.silva@gmail.com
BORGESWILLIA852@GMAIL.COM
yagofidalgo@gmail.com""".split("\n")

out = []
out.append("BEGIN;")
for old, new in zip(old_emails, new_emails):
    old = old.strip()
    new = new.strip()
    if old and new and old != new:
        out.append(f"UPDATE auth.users SET email = '{new}' WHERE email = '{old}';")
        out.append(f"UPDATE public.profiles SET email = '{new}' WHERE email = '{old}';")
out.append("COMMIT;")

with open("supabase/sql_trocar_emails_2026_03_30_v2.sql", "w") as f:
    f.write("\n".join(out))
print("Done!")
